export const randomItems = [
    "Apple", "Toyota Corolla", "Dog", "Laptop", "Coffee",
    "France", "Sunglasses", "Bicycle", "Book", "Banana",
    "Orange", "Ford Mustang", "Cat", "Smartphone", "Tea",
    "Germany", "Watch", "Running Shoes", "Magazine", "Grapes",
    "Pear", "Honda Civic", "Bird", "Headphones", "Juice",
    "Italy", "Backpack", "Tennis Racket", "Novel", "Watermelon",
    "Strawberry", "Chevrolet Silverado", "Fish", "Desktop Computer", "Soda",
    "Spain", "Necklace", "Golf Clubs", "Comic Book", "Pineapple",
    "Lemon", "Nissan Altima", "Turtle", "Tablet", "Beer",
    "Japan", "Earrings", "Soccer Ball", "Cookbook", "Cherry",
    "Water", "Jeep Wrangler", "Elephant", "Camera", "Milk",
    "Brazil", "Bracelet", "Basketball", "DVD", "Kiwi",
    "Mango", "Volkswagen Jetta", "Horse", "Printer", "Wine",
    "Australia", "Ring", "Baseball Bat", "Notebook", "Cucumber",
    "Potato", "Mercedes-Benz E-Class", "Lion", "Speaker", "Whiskey",
    "China", "Scarf", "Football", "Sketchbook", "Avocado",
    "Peach", "Audi A4", "Giraffe", "Microphone", "Coffee Maker",
    "India", "Hat", "Hiking Boots", "Calendar", "Olive Oil",
    "Onion", "BMW 3 Series", "Zebra", "Projector", "Chocolate",
    "Bread", "Mercedes-Benz C-Class", "Kangaroo", "Keyboard", "Smoothie",
    "Russia", "Purse", "Treadmill", "Board Game", "Blackberries",
    "Rice", "BMW 5 Series", "Ostrich", "Projector Screen", "Ice Cream",
    "Canada", "Cufflinks", "Hiking Backpack", "Easel", "Tomato",
    "Cabbage", "Toyota Prius", "Penguin", "Graphics Card", "Hot Chocolate",
    "Mexico", "Wallet", "Swimming Goggles", "MP3 Player", "Plum",
    "Walnut", "Audi Q5", "Rhinoceros", "Webcam", "Tequila",
    "South Africa", "Tie", "Jump Rope", "Oil Paints", "Apricot",
    "Lettuce", "Ford F-150", "Crocodile", "GPS Navigator", "Cocktail",
    "New Zealand", "Gloves", "Snowboard", "Watercolor Paints", "Pomegranate",
    "Broccoli", "Nissan Rogue", "Monkey", "External Hard Drive", "Lemonade",
    "South Korea", "T-Shirt", "Dumbbells", "Candle", "Peanut Butter",
    "Corn", "Chevrolet Equinox", "Gorilla", "Smart Watch", "Sushi",
    "Argentina", "Sandals", "Tent", "Sketch Pens", "Mango Juice",
    "Potato Chips", "Jeep Grand Cherokee", "Owl", "Drone", "Smoothie Maker",
    "Thailand", "Sunglasses Case", "Bicycle Helmet", "Stroller", "Gin",
    "Switzerland", "Perfume", "Ski Boots", "Binoculars", "Champagne",
    "Portugal", "Hairbrush", "Soccer Cleats", "Travel Guide", "Bacon",
    "Turkey", "Ford Explorer", "Seal", "Laser Printer", "Espresso Machine",
    "Ireland", "Earrings Box", "Roller Skates", "Fountain Pen", "Cranberries"
];